### ISSUE TITLE
Set ListItem icon (the title one at the left of the label)

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#20]
Hi Willforde,

Before switching to CodeQuick, we could modify the default ListItem icon in the listing. Do you know how we can do it with CodeQuick.

We already tested with `item.art['icon']` but without any effect.

Thank you for your help!

cc @wwark

<img width="1234" alt="capture d ecran 2018-11-14 a 17 34 28" src="https://user-images.githubusercontent.com/11562279/48497457-70032d80-e834-11e8-8ccb-049b5219708b.png">

Edit: Screenshot of our plugin with SimplePlugin:

<img width="1079" alt="capture d ecran 2018-11-14 a 19 40 58" src="https://user-images.githubusercontent.com/11562279/48504516-51596280-e845-11e8-8077-ce19db6fe184.png">

**Comment by willforde** [comment]
The reason it's working like that is because you have no content_type set, so CodeQuick defaults to "files/videos" depending on type of items, and the only way to get Kodi to work the way you want, is to not set any content_type at all. The "videos" content type is what is recommended by Kodi.

I have changed it now so you can disable the auto content_type by setting `plugin.content_type = None`.
